#! /usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use I74ifa\Vaid\Vaid;

if (empty($argv[1])){
    echo "not found directory project\n";
    exit;
}
$vhost = (new Vaid($argv));
echo $vhost->action() . "\n";